app/urls.py
from django.urls import path, include
from app.views import (
    IndexView,
    CreateAccountView,
    LoginView,
    GenerateOTPView,
    OTPVerificationView,
    RegisterView,
    RecordPlayView,
    SetupVoiceView,
    TapListenView,
    VerifyProceedView,
    ProvidersView,
    MobileRechargeView,
    BillFoundView,
    DTHRechargeView,
    MobilePostpaidView,
    LandlineView,
    ElectricityView,
    WaterView,
    PipedgasView,
    FASTagView,
    LoanRepaymentView,
    BroadbandView,
    LpgGasView,
    InsurancePaymentView,
    SubscriptionView,
    SendMoneyView,
    SendVoiceMoneyView,
    RequestMoneyView, 
    RequestVoiceMoneyView,
    VoiceAuthenticationView,
    ScanPayView,
    DashboardView,
    SettingView,
    PersonalInformationView,
    NotificationEmailsView,
    PrivacySecurityView,
    AboutView,
    HelpFeedbackView,
    EditMobileNumberView,
    EditLanguageView,
    DataPersonalizationView,
    BlockedPeopleView,
    HowPeopleView,
    TermsServicesView,
    PrivacyPolicyView,
    SoftwareLicenseView,
    UserProfileView,
    DrawNumberGameView,
    GetOTPFromVoiceView,
    LogoutView,
    GetNumberFromVoiceView,
    GetGameResultSuccessView,
    GetGameResultFailureView,
    AskToPlayGameView,
    PaymentSuccessfulView,
    InvoiceGeneratorView,
    DisplayInvoiceView,
    RequestSearchUserView,
    RequestSuccessView,
    RedirectView,
    RazorpayPaymentSuccessfulView,
    RazorpayPaymentUnsuccessfulView,
    RazorpayPaymentHandlerView,
    PayWithCCAvenueView,
    CCAvenueResponseView,
    CreateMerchantAccountView,
    MerchantRegistrationView,
    MerchantLoginView,
    MerchantDashboardView,
    ListProductsView,
    AddProductView,
    UpdateProductView,
    DeleteProductView,
    load_states,
    load_cities,
    ListProductVariationView,
    AddProductVariationView,
    DeleteProductVariationView,
    UpdateProductVariationsView,
    ListPurchaseView,
    AddPurchaseView,
    AddSaleView,
    AddSellReturnView,
    AddStockTransferView,
    AddStockAdjustmentsView,
    DeletePurchaseView,
    DeleteSellReturnView,
    DeleteSaleView,
    DeleteStockTransferView,
    DeleteStockAdjustmentView,
    AddExpenseView,
    DeleteExpenseView,
    AddExpenseCategoryView,
    DeleteExpenseCategoryView,
    AddTaxRatesView,
    UpdateTaxRatesView,
    DeleteTaxRatesView,
    AddBrandsView,
    UpdateBrandsView,
    DeleteBrandsView,
    AddUnitsView,
    UpdateUnitsView,
    DeleteUnitsView,
    AddTaxGroupView,
    DeleteTaxGroupView,
    OrderSummaryView,




    AboutUsView,
    ShopView,
    retrieveData,
    retrieveOneData,
    CheckoutView,
    AddCouponView,
    PaymentView,
    search,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    bycategoryelectronics,
    bycategorybooks,

)
from app import views


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create_account/', CreateAccountView.as_view(), name='create_account'),
    path('login/', LoginView.as_view(), name='paybill_login'),   
    path('otp/', GenerateOTPView.as_view(), name='otp'),
    path('otp/payment/', GenerateOTPView.as_view(), name='otp_payment'),
    path('otp_verification/', OTPVerificationView.as_view(), name='otp_verification'),   
    path('otp_payment_verification/', OTPVerificationView.as_view(), name='otp_payment_verification'),   
    path('otp_voice_verification/', GetOTPFromVoiceView.as_view(), name='otp_voice_verification'),    
    path('register/', RegisterView.as_view(), name='register'),
    path('record_play/', RecordPlayView.as_view(), name='record_play'),
    path('setup_voice/', SetupVoiceView.as_view(), name='setup_voice'),
    path('tap_listen/', TapListenView.as_view(), name='tap_listen'),
    path('verify_proceed/', VerifyProceedView.as_view(), name='verify_proceed'),
    path('aboutus/', AboutUsView.as_view(), name='aboutus'),
    path('providers/', ProvidersView.as_view(), name='providers'),
    path('providers/mobile_recharge/', MobileRechargeView.as_view(), name='mobile_recharge'),
    path('providers/bill_found/', BillFoundView.as_view(), name='bill_found'),
    path('providers/dth_recharge/', DTHRechargeView.as_view(), name='dth_recharge'),
    path('providers/mobile_postpaid/', MobilePostpaidView.as_view(), name='mobile_postpaid'),  
    path('providers/landline/', LandlineView.as_view(), name='landline'),  
    path('providers/electricity/', ElectricityView.as_view(), name='electricity'),  
    path('providers/water/', WaterView.as_view(), name='water'),  
    path('providers/piped_gas/', PipedgasView.as_view(), name='piped_gas'),  
    path('providers/FASTag/', FASTagView.as_view(), name='fastag'),  
    path('providers/loan_repayment/', LoanRepaymentView.as_view(), name='loan_repayment'),  
    path('providers/broadband/', BroadbandView.as_view(), name='broadband'),  
    path('providers/lpg_gas/', LpgGasView.as_view(), name='lpg_gas'),
    path('providers/insurance_payment/', InsurancePaymentView.as_view(), name='insurance_payment'),
    path('providers/subscription/', SubscriptionView.as_view(), name='subscription'),





    path('shop/', ShopView.as_view(), name='shop'),
    path('shopdetail/', retrieveData.as_view(), name='shop'), 
    path('shopdetail/<slug>/', retrieveOneData.as_view(), name='shopdetail'),
    path('search/', views.search, name='search'),
    path('category/books/', views.bycategorybooks, name='bycategorybooks'),
    path('category/electronics/', views.bycategoryelectronics, name='bycategoryelectronics'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),











    path('send_money/', SendMoneyView.as_view(), name='paybills_send_money'),
    path('send_voice_money/', SendVoiceMoneyView.as_view(), name='send_voice_money'),
    path('request_money/<int:user_id>', RequestMoneyView.as_view(), name='request_money'),
    path('request_voice_money/', RequestVoiceMoneyView.as_view(), name='request_voice_money'),
    path('voice_authentication/', VoiceAuthenticationView.as_view(), name='voice_authentication'),
    path('scan_pay/', ScanPayView.as_view(), name='scan_pay'), 
    path('dashboard/', DashboardView.as_view(), name='dashboard'), 
    path('setting/', SettingView.as_view(), name='setting'), 
    path('personal_info/', PersonalInformationView.as_view(), name='personal_info'), 
    path('notification_email/', NotificationEmailsView.as_view(), name='notification_email'), 
    path('privacy_security/', PrivacySecurityView.as_view(), name='privacy_security'), 
    path('about/', AboutView.as_view(), name='about'), 
    path('help_feedback/', HelpFeedbackView.as_view(), name='help_feedback'), 
    path('personal_info/edit_mobile_number/', EditMobileNumberView.as_view(), name='edit_mobile_number'), 
    path('personal_info/edit_language/', EditLanguageView.as_view(), name='edit_language'),      
    path('privacy_security/data_personalization/', DataPersonalizationView.as_view(), name='data_personalization'),      
    path('privacy_security/blocked_people/', BlockedPeopleView.as_view(), name='blocked_people'),      
    path('privacy_security/how_people_find_you/', HowPeopleView.as_view(), name='how_people_find_you'),      
    path('about/terms_services/', TermsServicesView.as_view(), name='terms_services'),      
    path('about/privacy_policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),      
    path('about/software_license/', SoftwareLicenseView.as_view(), name='software_license'), 
    path('dashboard/user_profile/', UserProfileView.as_view(), name='user_profile'),      
    path('draw_number_game/', DrawNumberGameView.as_view(), name='draw_number_game'),      
    path('get_number_game/', GetNumberFromVoiceView.as_view(), name='get_number_game'),      
    path('logout/', LogoutView.as_view(), name='logout'),
    path('get_game_result_success/', GetGameResultSuccessView.as_view(), name='get_game_result_success'),
    path('get_game_result_failure/', GetGameResultFailureView.as_view(), name='get_game_result_failure'),
    path('ask_to_play_game/', AskToPlayGameView.as_view(), name='ask_to_play_game'),
    path('payment_successful/', PaymentSuccessfulView.as_view(), name='payment_successful'),    
    path('get_invoice/', InvoiceGeneratorView.as_view(), name='get_invoice'),
    path('display_invoice/<int:bill_id>/', DisplayInvoiceView.as_view(), name='display_invoice'),
    path('search_user/', RequestSearchUserView.as_view(), name='search_user'),
    path('request_successful/', RequestSuccessView.as_view(), name='request_successful'),    
    path('send_money/', SendMoneyView.as_view(), name='paybills_send_money'), 
    path('send_money/razorpay_payment_handler/', RazorpayPaymentHandlerView.as_view(), name='razorpay_payment_handler'), 
    path('razorpay_payment_successful/', RazorpayPaymentSuccessfulView.as_view(), name='razorpay_payment_successful'),
    path('razorpay_payment_unsuccessful/', RazorpayPaymentUnsuccessfulView.as_view(), name='razorpay_payment_unsuccessful'),
    #path('razorpay_payment/',PayWithRazorpayView.as_view(), name='razorpay_payment'),
    path('ccavenue_payment/',PayWithCCAvenueView.as_view(), name='ccavenue_payment'),
    path('ccavenue_response/', CCAvenueResponseView.as_view(), name='ccavenue_response'),
    #path('create_merchant_account/', CreateMerchantAccountView.as_view(), name='create_merchant_account'),
    path('create_merchant_account/', MerchantRegistrationView.as_view(), name='create_merchant_account'),

paybills/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
"""
from app.views import (
    UserLogin,
    UserLogout,
    UserRegistration,
    UserResetPwd,
)
"""

urlpatterns = [
    #path('', RedirectView.as_view(pattern_name='index')),

    #path('admin/', admin.site.urls),
    path('paybills_admin/', admin.site.urls),
    #path('login/', UserLogin.as_view(template_name='app/login.html'), name='user_login'),
    #path('logout/', UserLogout.as_view(), name='user_logout'),
    #path('registration/', UserRegistration.as_view(), name='registration'),
    #path('reset-password/', UserResetPwd.as_view(), name='reset_password'),
    #path('paypal/', include('paypal.standard.ipn.urls')),    
    # path('', include('app.urls')),
    path('', include(('app.urls', 'app'), namespace='app')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/templates/app/shop/category.html
{% extends 'shop/index.html' %}



{% block shopdetail %}


{% load static %}

<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

<main role="main">

    
    <div class="album py-5 bg-light">
      <div class="container">
        
        <div class="row">




          {% for product in sproducts %}

          <div class="col-md-4">
            <div class="card mb-4 box-shadow" style="">
              
              <div class="mycontainer">
                
                <img class="card-img-top" src = "{{ product.product_image.url }}" style="" data-holder-rendered="true">
                

              </div>
              
              <div class="card-body">
                <p class="card-text">
                  merchant = {{product.merchant.merchant}}<br>
                  Product Name = {{product.product_name}}<br>
                  

                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    
                    <a href="{% url 'app:shopdetail' product.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary" >{{product.product_name}}</button></a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">{{product.product_price}}</button>
                  </div>
                  <small class="text-muted">{{product.product_SKU}}</small>
                </div>
              </div>
            </div>
          </div>
        
          {% endfor %}

         
        
         
          
        </div>
      </div>
    </div>


  </main>

{% endblock %}

app/templates/app/shop/navbar.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!--Main Navigation-->
<header class="mb-5">
    <!-- Jumbotron -->
    <div class="p-3 text-center text-white" style="background-color: #94D6F6">
      <div class="container">
        <div class="row">
          <div class="col-md-4 d-flex justify-content-center justify-content-md-start mb-3 mb-md-0">
            <a href="/providers/" class="ms-md-2">
              <img src="{% static "assets/img/logo.png" %}"  />
            </a>
          </div>
  
          <div class="col-md-4">
            <form class="d-flex input-group w-auto my-auto mb-3 mb-md-0" method="get" action="/search">
              <input autocomplete="off" type="search" class="form-control rounded" placeholder="Search" style="margin-top: 10px;" name="query" id="query"/>
              <span class="input-group-text border-0 d-none d-lg-flex" style="margin-top: 10px;"><i class="fas fa-search text-white"></i></span>
            </form>
          </div>
  
          <div class="col-md-4 d-flex justify-content-center justify-content-md-end align-items-center">
            <div class="d-flex">
             
              <!-- User -->
              <div class="dropdown">
                <a data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" >
                  <img src="{% static "assets/img/sample/avatar/img_avatar.png" %}" class="rounded-circle" height="40" alt=""
                    loading="lazy" />
                </a>
                <ul class="dropdown-menu" >
                  <li><a class="dropdown-item" href="#">My profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'app:setting' %}">Settings</a></li>
                  <li><a class="dropdown-item" href="{% url 'app:logout' %}">Logout</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Jumbotron -->
  
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0076ba">
      <!-- Container wrapper -->
      <div class="container justify-content-center justify-content-md-between">
        <!-- Left links -->
        <ul class="navbar-nav flex-row">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" >
              <i class="fas fa-bars me-1"></i>
              <span style="font-size: 20px">Categories</span>
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Fashion</a></li>
                <li><a class="dropdown-item" href="{% url 'app:bycategoryelectronics' %}">Electronics</a></li>
                <li><a class="dropdown-item" href="{% url 'app:bycategorybooks' %}">Books</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Grocery</a></li>
              </ul>
            
          </li>

          <li class="nav-item me-2 me-lg-0 d-none d-md-inline-block">
            <a class="nav-link" href="#" style="font-size: 20px; margin-left: 5px;">Bestsellers</a>
          </li>
          <li class="nav-item me-2 me-lg-0 d-none d-md-inline-block">
            <a class="nav-link" href="#" style="font-size: 20px; margin-left: 5px;">Inspirations</a>
          </li>
          <li class="nav-item me-2 me-lg-0 d-none d-md-inline-block">
            <a class="nav-link" href="#" style="font-size: 20px; margin-left: 5px;">Blog</a>
          </li>
          <li class="nav-item me-2 me-lg-0 d-none d-md-inline-block">
            <a class="nav-link" href="#" style="font-size: 20px; margin-left: 5px;">Contact</a>
          </li>
        </ul>
        <!-- Left links -->
  
        <button class="btn btn-outline-light" type="button">
          Download Paybills<i class="fas fa-download ms-2"></i>
        </button>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  
 
  
  </header>
  <!--Main Navigation-->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

app/templates/app/shop/one.html
{% extends 'shop/index.html' %}

{% block shopdetail %}

{% load static %}

merchant = {{object.merchant.merchant}}<br>

 

 product_description = {{object.product_description}}<br>
 product_name = {{object.product_name}}<br>
 product_stock = {{object.product_stock}}<br>
 product_price = {{object.product_price}}<br>
 category_name = {{object.product_category.category_name}}<br>
 subcategory_name = {{object.product_subcategory.subcategory_name}}<br>
 product_price = {{object.product_price}}<br>
 image = <img src = "{{ object.product_image.url }}" width="20%"><br>
 image = <img src = "{{ object.product_image2.url }}" width="20%"><br>
 image = <img src = "{{ object.product_image3.url }}" width="20%"> <br><br>







{% comment %} 
 <div class="item-slick3" data-thumb="{{ object.product_image.url }}">
    <div class="wrap-pic-w">
        <img src="{{object.product_image.url}}" alt="{{ object.title }}"">
    </div>
 </div> {% endcomment %}



 choose one option: <br> <br>
 <a href="{% url 'app:ask_to_play_game' object.slug %}"> Play Game </a> <br> <br> <br>
 <a href="#"> Flat Discount </a> <br> <br> <br> 
 <a href="#"> Pay with EMI </a> <br> <br> <br> 







{% endblock %}

app/templates/app/shop/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">Rs {{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
         <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          {% comment %} <span class="text-success">-Rs {{ order.coupon.amount }}</span> {% endcomment %}
          <span class="text-success"> 50% off </span> 
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (INR)</span>
          <strong>Rs {{ order.get_total }}</strong>
        </li>
      </ul>  
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'app:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

app/templates/app/shop/product.html
{% extends 'shop/index.html' %}



{% block shopdetail %}


{% load static %}

<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

<main role="main">

    <section class="jumbotron text-center" style="padding-top: 30px; padding-bottom: 30px">
      <div class="container">
        <h1 class="jumbotron-heading">Welcome to the Paybills Shop</h1>
        <p class="lead text-muted">Paybills is a one stop shop for all your fashion and lifestyle needs. Being India's newest e-commerce store for fashion and lifestyle products, Paybills aims at providing a hassle free and enjoyable shopping experience to shoppers across the country with the widest range of brands and products on its portal. </p>
{% comment %}         
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
         {% endcomment %}
      </div>
    </section>

    
    <div class="album py-5 bg-light">
      <div class="container">
        
        <div class="row">

          {% for product in object_list %}

          <div class="col-md-4">
            <div class="card mb-4 box-shadow" style="width: 340px">
              <img class="card-img-top" src = "{{ product.product_image.url }}" alt="Thumbnail [100%x225]" style="display: block; width: 338px; height: 400px ;"  data-holder-rendered="true">
              <div class="card-body">
                <p class="card-text">
                  merchant = {{product.merchant.merchant}}<br>
                  Product = {{product.product_name}}<br>
                  

                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    
                    <a href="{% url 'app:shopdetail' product.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary" >{{product.product_name}}</button></a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">{{product.product_price}}</button>
                  </div>
                  <small class="text-muted">{{product.product_SKU}}</small>
                </div>
              </div>
            </div>
          </div>


          
          
          
          {% comment %} <div class="wrap-pic-w">
            <img src="{{ product.product_image.url }}" alt="{{ product.product_name }}">
          </div> {% endcomment %}


        
          {% endfor %}

         
        
         
          
        </div>
      </div>
    </div>

  </main>


{% comment %} 



<img src="{{ item.product_image }}" alt="IMG-PRODUCT" 
style="height: 360px;">
<br>
merchant = {{item.merchant.merchant}}<br>
product_description = {{item.product_description}}<br>
product_name = {{item.product_name}}<br>
product_stock = {{item.product_stock}}<br>
product_price = {{item.product_price}}<br>
category_name = {{item.product_category.category_name}}<br>
subcategory_name = {{item.product_subcategory.subcategory_name}}<br>
product_price = {{item.product_price}}<br>
--------------------------------------------------------------------------------- {% endcomment %}



{% endblock %}

app/templates/app/shop/search.html
{% extends 'shop/index.html' %}

{% load static %}

{% block shopdetail %}



<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/album/">

<main role="main">

    
    <div class="album py-5 bg-light">
      <div class="container">
        
        <div class="row">




          {% for product in sproducts %}

          <div class="col-md-4">
            <div class="card mb-4 box-shadow" style="width: 352px">
              <img class="card-img-top" src = "{{ product.product_image.url }}" alt="Thumbnail [100%x225]" style="height: 100%; width: 100%; display: block;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22348%22%20height%3D%22226%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20348%20226%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_17f8c620c0d%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A17pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_17f8c620c0d%22%3E%3Crect%20width%3D%22348%22%20height%3D%22226%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22116.71249771118164%22%20y%3D%22120.68000011444092%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
              <div class="card-body">
                <p class="card-text">
                  merchant = {{product.merchant.merchant}}<br>
                  Product Name = {{product.product_name}}<br>
                  slug = {{product.slug}}

                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    
                    <a href="{% url 'app:shopdetail' product.slug %}"><button type="button" class="btn btn-sm btn-outline-secondary" >{{product.product_name}}</button></a>
                    <button type="button" class="btn btn-sm btn-outline-secondary">{{product.product_price}}</button>
                  </div>
                  <small class="text-muted">{{product.product_SKU}}</small>
                </div>
              </div>
            </div>
          </div>
        
          {% endfor %}

         
        
         
          
        </div>
      </div>
    </div>

  </main>



{% endblock %}