app/urls.py
from django.urls import path, include
from app.views import (
    IndexView,
    CreateAccountView,
    LoginView,
    GenerateOTPView,
    OTPVerificationView,
    RegisterView,
    RecordPlayView,
    SetupVoiceView,
    TapListenView,
    VerifyProceedView,
    ProvidersView,
    MobileRechargeView,
    BillFoundView,
    DTHRechargeView,
    MobilePostpaidView,
    LandlineView,
    ElectricityView,
    WaterView,
    PipedgasView,
    FASTagView,
    LoanRepaymentView,
    BroadbandView,
    LpgGasView,
    InsurancePaymentView,
    SubscriptionView,
    SendMoneyView,
    SendVoiceMoneyView,
    RequestMoneyView, 
    RequestVoiceMoneyView,
    VoiceAuthenticationView,
    ScanPayView,
    DashboardView,
    SettingView,
    PersonalInformationView,
    NotificationEmailsView,
    PrivacySecurityView,
    AboutView,
    HelpFeedbackView,
    EditMobileNumberView,
    EditLanguageView,
    DataPersonalizationView,
    BlockedPeopleView,
    HowPeopleView,
    TermsServicesView,
    PrivacyPolicyView,
    SoftwareLicenseView,
    UserProfileView,
    DrawNumberGameView,
    GetOTPFromVoiceView,
    LogoutView,
    GetNumberFromVoiceView,
    GetGameResultSuccessView,
    GetGameResultFailureView,
    AskToPlayGameView,
    PaymentSuccessfulView,
    InvoiceGeneratorView,
    DisplayInvoiceView,
    RequestSearchUserView,
    RequestSuccessView,
    RedirectView,
    RazorpayPaymentSuccessfulView,
    RazorpayPaymentUnsuccessfulView,
    RazorpayPaymentHandlerView,
    PayWithCCAvenueView,
    CCAvenueResponseView,
    CreateMerchantAccountView,
    MerchantRegistrationView,
    MerchantLoginView,
    MerchantDashboardView,
    ListProductsView,
    AddProductView,
    UpdateProductView,
    DeleteProductView,
    load_states,
    load_cities,
    ListProductVariationView,
    AddProductVariationView,
    DeleteProductVariationView,
    UpdateProductVariationsView,
    ListPurchaseView,
    AddPurchaseView,
    AddSaleView,
    AddSellReturnView,
    AddStockTransferView,
    AddStockAdjustmentsView,
    DeletePurchaseView,
    DeleteSellReturnView,
    DeleteSaleView,
    DeleteStockTransferView,
    DeleteStockAdjustmentView,
    AddExpenseView,
    DeleteExpenseView,
    AddExpenseCategoryView,
    DeleteExpenseCategoryView,
    AddTaxRatesView,
    UpdateTaxRatesView,
    DeleteTaxRatesView,
    AddBrandsView,
    UpdateBrandsView,
    DeleteBrandsView,
    AddUnitsView,
    UpdateUnitsView,
    DeleteUnitsView,
    AddTaxGroupView,
    DeleteTaxGroupView,
    OrderSummaryView,




    AboutUsView,
    ShopView,
    retrieveData,
    retrieveOneData,
    CheckoutView,
    AddCouponView,
    PaymentView,
    search,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    bycategoryelectronics,
    bycategorybooks,

)
from app import views


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create_account/', CreateAccountView.as_view(), name='create_account'),
    path('login/', LoginView.as_view(), name='paybill_login'),   
    path('otp/', GenerateOTPView.as_view(), name='otp'),
    path('otp/payment/', GenerateOTPView.as_view(), name='otp_payment'),
    path('otp_verification/', OTPVerificationView.as_view(), name='otp_verification'),   
    path('otp_payment_verification/', OTPVerificationView.as_view(), name='otp_payment_verification'),   
    path('otp_voice_verification/', GetOTPFromVoiceView.as_view(), name='otp_voice_verification'),    
    path('register/', RegisterView.as_view(), name='register'),
    path('record_play/', RecordPlayView.as_view(), name='record_play'),
    path('setup_voice/', SetupVoiceView.as_view(), name='setup_voice'),
    path('tap_listen/', TapListenView.as_view(), name='tap_listen'),
    path('verify_proceed/', VerifyProceedView.as_view(), name='verify_proceed'),
    path('aboutus/', AboutUsView.as_view(), name='aboutus'),
    path('providers/', ProvidersView.as_view(), name='providers'),
    path('providers/mobile_recharge/', MobileRechargeView.as_view(), name='mobile_recharge'),
    path('providers/bill_found/', BillFoundView.as_view(), name='bill_found'),
    path('providers/dth_recharge/', DTHRechargeView.as_view(), name='dth_recharge'),
    path('providers/mobile_postpaid/', MobilePostpaidView.as_view(), name='mobile_postpaid'),  
    path('providers/landline/', LandlineView.as_view(), name='landline'),  
    path('providers/electricity/', ElectricityView.as_view(), name='electricity'),  
    path('providers/water/', WaterView.as_view(), name='water'),  
    path('providers/piped_gas/', PipedgasView.as_view(), name='piped_gas'),  
    path('providers/FASTag/', FASTagView.as_view(), name='fastag'),  
    path('providers/loan_repayment/', LoanRepaymentView.as_view(), name='loan_repayment'),  
    path('providers/broadband/', BroadbandView.as_view(), name='broadband'),  
    path('providers/lpg_gas/', LpgGasView.as_view(), name='lpg_gas'),
    path('providers/insurance_payment/', InsurancePaymentView.as_view(), name='insurance_payment'),
    path('providers/subscription/', SubscriptionView.as_view(), name='subscription'),





    path('shop/', ShopView.as_view(), name='shop'),
    path('shopdetail/', retrieveData.as_view(), name='shop'), 
    path('shopdetail/<slug>/', retrieveOneData.as_view(), name='shopdetail'),
    path('search/', views.search, name='search'),
    path('category/books/', views.bycategorybooks, name='bycategorybooks'),
    path('category/electronics/', views.bycategoryelectronics, name='bycategoryelectronics'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),











    path('send_money/', SendMoneyView.as_view(), name='paybills_send_money'),
    path('send_voice_money/', SendVoiceMoneyView.as_view(), name='send_voice_money'),
    path('request_money/<int:user_id>', RequestMoneyView.as_view(), name='request_money'),
    path('request_voice_money/', RequestVoiceMoneyView.as_view(), name='request_voice_money'),
    path('voice_authentication/', VoiceAuthenticationView.as_view(), name='voice_authentication'),
    path('scan_pay/', ScanPayView.as_view(), name='scan_pay'), 
    path('dashboard/', DashboardView.as_view(), name='dashboard'), 
    path('setting/', SettingView.as_view(), name='setting'), 
    path('personal_info/', PersonalInformationView.as_view(), name='personal_info'), 
    path('notification_email/', NotificationEmailsView.as_view(), name='notification_email'), 
    path('privacy_security/', PrivacySecurityView.as_view(), name='privacy_security'), 
    path('about/', AboutView.as_view(), name='about'), 
    path('help_feedback/', HelpFeedbackView.as_view(), name='help_feedback'), 
    path('personal_info/edit_mobile_number/', EditMobileNumberView.as_view(), name='edit_mobile_number'), 
    path('personal_info/edit_language/', EditLanguageView.as_view(), name='edit_language'),      
    path('privacy_security/data_personalization/', DataPersonalizationView.as_view(), name='data_personalization'),      
    path('privacy_security/blocked_people/', BlockedPeopleView.as_view(), name='blocked_people'),      
    path('privacy_security/how_people_find_you/', HowPeopleView.as_view(), name='how_people_find_you'),      
    path('about/terms_services/', TermsServicesView.as_view(), name='terms_services'),      
    path('about/privacy_policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),      
    path('about/software_license/', SoftwareLicenseView.as_view(), name='software_license'), 
    path('dashboard/user_profile/', UserProfileView.as_view(), name='user_profile'),      
    path('draw_number_game/', DrawNumberGameView.as_view(), name='draw_number_game'),      
    path('get_number_game/', GetNumberFromVoiceView.as_view(), name='get_number_game'),      
    path('logout/', LogoutView.as_view(), name='logout'),
    path('get_game_result_success/', GetGameResultSuccessView.as_view(), name='get_game_result_success'),
    path('get_game_result_failure/', GetGameResultFailureView.as_view(), name='get_game_result_failure'),
    path('ask_to_play_game/', AskToPlayGameView.as_view(), name='ask_to_play_game'),
    path('payment_successful/', PaymentSuccessfulView.as_view(), name='payment_successful'),    
    path('get_invoice/', InvoiceGeneratorView.as_view(), name='get_invoice'),
    path('display_invoice/<int:bill_id>/', DisplayInvoiceView.as_view(), name='display_invoice'),
    path('search_user/', RequestSearchUserView.as_view(), name='search_user'),
    path('request_successful/', RequestSuccessView.as_view(), name='request_successful'),    
    path('send_money/', SendMoneyView.as_view(), name='paybills_send_money'), 
    path('send_money/razorpay_payment_handler/', RazorpayPaymentHandlerView.as_view(), name='razorpay_payment_handler'), 
    path('razorpay_payment_successful/', RazorpayPaymentSuccessfulView.as_view(), name='razorpay_payment_successful'),
    path('razorpay_payment_unsuccessful/', RazorpayPaymentUnsuccessfulView.as_view(), name='razorpay_payment_unsuccessful'),
    #path('razorpay_payment/',PayWithRazorpayView.as_view(), name='razorpay_payment'),
    path('ccavenue_payment/',PayWithCCAvenueView.as_view(), name='ccavenue_payment'),
    path('ccavenue_response/', CCAvenueResponseView.as_view(), name='ccavenue_response'),
    #path('create_merchant_account/', CreateMerchantAccountView.as_view(), name='create_merchant_account'),
    path('create_merchant_account/', MerchantRegistrationView.as_view(), name='create_merchant_account'),

paybills/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
"""
from app.views import (
    UserLogin,
    UserLogout,
    UserRegistration,
    UserResetPwd,
)
"""

urlpatterns = [
    #path('', RedirectView.as_view(pattern_name='index')),

    #path('admin/', admin.site.urls),
    path('paybills_admin/', admin.site.urls),
    #path('login/', UserLogin.as_view(template_name='app/login.html'), name='user_login'),
    #path('logout/', UserLogout.as_view(), name='user_logout'),
    #path('registration/', UserRegistration.as_view(), name='registration'),
    #path('reset-password/', UserResetPwd.as_view(), name='reset_password'),
    #path('paypal/', include('paypal.standard.ipn.urls')),    
    # path('', include('app.urls')),
    path('', include(('app.urls', 'app'), namespace='app')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/templates/app/common/get-invoice.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>Paybills - Invoice</title>
    <meta name="description" content="Paybills - Invoice">
    <meta name="keywords" content="bootstrap 4, mobile template, cordova, phonegap, mobile, html" />
    <link rel="icon" type="image/png" href="{% static "assets/img/favicon.png" %}" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "assets/img/icon/192x192.png" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link rel="manifest" href="__manifest.json">
</head>

<body>

    <!-- loader -->
    <div id="loader">
        <div class="spinner-border text-primary" role="status"></div>
    </div>
    <!-- * loader -->

    <!-- App Capsule -->
    <div id="appCapsule" class="pt-0">
        <div class="top-logo">
            <img src="{% static "assets/img/logo.png" %}">
        </div>
        <div class="register-bg">
            <img src="{% static "assets/img/register-bg.png" %}">
        </div>
        <div class="register-box">
            <h1>
                Invoice generated sucessfully.
            </h1>
            <div class="register-btn-div">
                <a href="{% url 'app:display_invoice' bill_id=bill_id %}" class="btn complete-reg-btn">
                   Display Invoice
                </a>    
            </div>
            <div class="register-btn-div">
                <a href="{% url 'app:providers' %}" class="btn complete-reg-btn">
                   Back to Providers
                </a>    
            </div>
        </div>               
    </div>
    <!-- * App Capsule -->

    <!-- ///////////// Js Files ////////////////////  -->
    <!-- Jquery -->
    <script src="{% static "assets/js/lib/jquery-3.4.1.min.js" %}"></script>

    <!-- Bootstrap-->
    <script src="{% static "assets/js/lib/popper.min.js" %}"></script>
    <script src="{% static "assets/js/lib/bootstrap.min.js" %}"></script>
    <!-- Ionicons -->
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>
    <!-- Owl Carousel -->
    <script src="{% static "assets/js/plugins/owl-carousel/owl.carousel.min.js" %}"></script>
    <!-- jQuery Circle Progress -->
    <script src="{% static "assets/js/plugins/jquery-circle-progress/circle-progress.min.js" %}"></script>
    <!-- Base Js File -->
    <script src="{% static "assets/js/base.js" %}"></script>


    <script>
        setTimeout(() => {
            notification('notification-welcome', 5000);
        }, 2000);
    </script>

</body>

</html>

app/templates/app/common/loan-repayment.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>Paybills - Loan Repayment</title>
    <meta name="description" content="Paybills - Loan Repayment">
    <meta name="keywords" content="bootstrap 4, mobile template, cordova, phonegap, mobile, html" />
    <link rel="icon" type="image/png" href="{% static "assets/img/favicon.png" %}" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "assets/img/icon/192x192.png" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link rel="manifest" href="__manifest.json">
</head>

<body>

    <!-- loader -->
    <div id="loader">
        <div class="spinner-border text-primary" role="status"></div>
    </div>
    <!-- * loader -->

    <div class="appHeader bg-primary text-light">
        <div class="left">
            <a href="{% url 'app:providers' %}" class="headerButton goBack">
                <ion-icon name="chevron-back-outline" role="img" class="md hydrated" aria-label="chevron back outline"></ion-icon>
            </a>
        </div>
        <div class="pageTitle">Loan Repayment </div>
        <div class="right">
        </div>
    </div>

    <!-- App Capsule -->
    <div id="appCapsule">
        <div class="top-logo">
            <img src="{% static "assets/img/logo.png" %}">
        </div>
        <div class="register-bg">
            <img src="{% static "assets/img/register-bg.png" %}">
        </div>
        <div class="register-box">
            <h1>
                Loan Repayment
            </h1>
            <div class="upi-box">
                <div class="form-group">
                    <label>
                        Provider
                    </label>
                    <select class="form-control custom-select">
                        <option selected disabled value="">Choose...</option>
                        <option value="226" data-select2-id="69">Capri Global Housing Finance
                        </option><option value="227" data-select2-id="70">Cars24 Financial Services Private Limited
                        </option><option value="228" data-select2-id="71">Avanse Financial Services Ltd
                        </option><option value="229" data-select2-id="72">Shriram City  Union Finance Ltd
                        </option><option value="230" data-select2-id="73">Arohan Financial Services Ltd
                        </option><option value="231" data-select2-id="74">OHMYLOAN
                        </option><option value="232" data-select2-id="75">IDFC FIRST Bank Ltd
                        </option><option value="233" data-select2-id="76">Annapurna Finance Private Limited-MSME
                        </option><option value="234" data-select2-id="77">Hero FinCorp Limited
                        </option><option value="235" data-select2-id="78">i2i Funding-Borrower EMI Repayment
                        </option><option value="236" data-select2-id="79">Muthoot Microfin Limited
                        </option><option value="237" data-select2-id="80">Shriram Housing Finance Limited
                        </option><option value="238" data-select2-id="81">Jana Small Finance Bank
                        </option><option value="239" data-select2-id="82">Fullerton India Housing Finance Limited
                        </option><option value="240" data-select2-id="83">L&amp;T Financial Services
                        </option><option value="241" data-select2-id="84">Manappuram Finance Limited-Vehicle Loan
                        </option><option value="242" data-select2-id="85">Loksuvidha
                        </option><option value="243" data-select2-id="86">Axis Finance Limited
                        </option><option value="244" data-select2-id="87">India Shelter Finance Corporation Limited
                        </option><option value="245" data-select2-id="88">L and T Housing Finance
                        </option><option value="246" data-select2-id="89">AAVAS FINANCIERS LIMITED
                        </option><option value="247" data-select2-id="90">Kinara Capital
                        </option><option value="248" data-select2-id="91">DMI Finance Private Limited
                        </option><option value="249" data-select2-id="92">Ess Kay Fincorp Limited
                        </option><option value="250" data-select2-id="93">Kissht
                        </option><option value="251" data-select2-id="94">Bajaj Auto Finance
                        </option><option value="252" data-select2-id="95">Fincare Small Finance Bank
                        </option><option value="253" data-select2-id="96">ZestMoney
                        </option><option value="254" data-select2-id="97">OMLP2P.COM
                        </option><option value="255" data-select2-id="98">Annapurna Finance Private Limited-MFI
                        </option><option value="256" data-select2-id="99">Bajaj Finance
                        </option><option value="257" data-select2-id="100">Muthoot Capital Services Ltd
                        </option><option value="258" data-select2-id="101">Easy Home Finance Limited
                        </option><option value="259" data-select2-id="102">Faircent-Borrower EMI Account
                        </option><option value="260" data-select2-id="103">Tata Capital Financial Services Limited
                        </option><option value="261" data-select2-id="104">Aditya Birla Housing Finance Limited
                        </option><option value="262" data-select2-id="105">Varthana
                        </option><option value="263" data-select2-id="106">LOANTAP CREDIT PRODUCTS PRIVATE LIMITED
                        </option><option value="264" data-select2-id="107">Toyota Financial Services
                        </option><option value="265" data-select2-id="108">Snapmint
                        </option><option value="266" data-select2-id="109">Paisa Dukan-Borrower EMI
                        </option><option value="267" data-select2-id="110">Kanakadurga Finance Limited
                        </option><option value="268" data-select2-id="111">Mahindra Rural Housing Finance Ltd
                        </option><option value="269" data-select2-id="112">Capri Global Capital Limited
                        </option><option value="270" data-select2-id="113">ICICI Bank Ltd - Loans
                        </option><option value="271" data-select2-id="114">AU Bank Loan Repayment
                        </option><option value="272" data-select2-id="115">Shriram Transport Finance Company Limited
                        </option><option value="273" data-select2-id="116">Vastu Housing Finance Corporation Limited
                        </option><option value="274" data-select2-id="117">Avail
                        </option><option value="275" data-select2-id="118">Flexsalary
                        </option><option value="276" data-select2-id="119">Fullerton India credit company limited
                        </option><option value="277" data-select2-id="120">Adani Capital Pvt Ltd
                        </option><option value="278" data-select2-id="121">BERAR Finance Limited
                        </option><option value="279" data-select2-id="122">G U Financial Services Pvt Ltd
                        </option><option value="280" data-select2-id="123">Indiabulls Consumer Finance Limited
                        </option><option value="281" data-select2-id="124">Indiabulls Housing Finance Limited
                        </option><option value="282" data-select2-id="125">Jain Autofin
                        </option><option value="283" data-select2-id="126">RupeeRedee
                        </option><option value="284" data-select2-id="127">Clix
                        </option><option value="285" data-select2-id="128">Baid Leasing and Finance
                        </option><option value="286" data-select2-id="129">Motilal Oswal Home Finance
                        </option><option value="287" data-select2-id="130">Oxyzo Financial Services Pvt Ltd
                        </option><option value="341" data-select2-id="131">Home Credit India Finance Pvt. Ltd
                        </option></select>
                </div>
                <div class="form-group">
                    <label>Customer Mobile Number</label>
                    <input class="form-control custom-input" placeholder="Customer Mobile Number">
                </div>
                <div class="form-group">
                    <label>Loan Account Number</label>
                    <input class="form-control custom-input" placeholder="Customer ID">
                </div>
            </div>
            <div class="register-btn-div">
                <a href="{% url 'app:bill_found' %}" class="btn complete-reg-btn">
                    Continue
                </a>
            </div>
        </div>
    </div>
    <!-- * App Capsule -->

    <!-- ///////////// Js Files ////////////////////  -->
    <!-- Jquery -->
    <script src="{% static "assets/js/lib/jquery-3.4.1.min.js" %}"></script>
    <!-- Bootstrap-->
    <script src="{% static "assets/js/lib/popper.min.js" %}"></script>
    <script src="{% static "assets/js/lib/bootstrap.min.js" %}"></script>
    <!-- Ionicons -->
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>
    <!-- Owl Carousel -->
    <script src="{% static "assets/js/plugins/owl-carousel/owl.carousel.min.js" %}"></script>
    <!-- jQuery Circle Progress -->
    <script src="{% static "assets/js/plugins/jquery-circle-progress/circle-progress.min.js" %}"></script>
    <!-- Base Js File -->
    <script src="{% static "assets/js/base.js" %}"></script>


    <script>
        setTimeout(() => {
            notification('notification-welcome', 5000);
        }, 2000);
    </script>

</body>

</html>

app/templates/app/common/login.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="theme-color" content="#000000">
    <title>Paybills - Login</title>
    <meta name="description" content="Mobilekit HTML Mobile UI Kit">
    <meta name="keywords" content="bootstrap 4, mobile template, cordova, phonegap, mobile, html" />
    <link rel="icon" type="image/png" href="{% static "assets/img/favicon.png" %}" sizes="32x32">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "assets/img/icon/192x192.png" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link rel="manifest" href="__manifest.json">
</head>

<body>

    <!-- loader -->
    <div id="loader">
        <div class="spinner-border text-primary" role="status"></div>
    </div>
    <!-- * loader -->

    <!-- App Capsule -->
    <div id="appCapsule">
        <div class="top-logo">
            <img src="{% static "assets/img/logo.png" %}">
        </div>
        <div class="register-bg">
            <img src="{% static "assets/img/register-bg.png" %}">
        </div>
        <div class="register-box">
            <h1>
                Login
            </h1>
            <form class="form-contact contact_form" action="#" method="post" id="loginForm">
                {% csrf_token %}
                {% if form.errors %}                
                    <p>Please correct the following errors:</p>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error|escape }}</li>
                        {% endfor %}
                    {% endfor %}

                    {% for error in form.non_field_errors %}
                        <li> {{ error|escape }}</li>
                    {% endfor %}

                    {% for message in messages %}
                        <li> {{ message }}</li>
                    {% endfor %}                
                {% endif %}

                <div class="upi-box">
                    <div class="form-group">
                        <input class="form-control custom-input" placeholder="Email" name="{{ form.email.html_name }}" id="{{ form.email.id_for_label }}" required>
                        {{ form.email.errors }}
                    </div>
                    <div class="form-group">
                        <input class="form-control" placeholder="Password" type="password" name="{{ form.password.html_name }}" id="{{ form.password.id_for_label }}" required>
                        <button class="btn eye-btn"><ion-icon name="eye"></ion-icon></button>
                        {{ form.password.errors }}
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <div class="remember-check custom-control custom-checkbox mb-1">
                                <input type="checkbox" class="custom-control-input" id="customCheckb1">
                                <label class="custom-control-label" for="customCheckb1">Remember</label>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="forget-pass-div">
                                <a href="#">Forgot password?</a>
                            </div>
                        </div>
                    </div>
                </div>
            
                <div class="register-btn-div">
                    <!-- <a href="{% url 'app:otp' %}" class="btn complete-reg-btn">
                        Login
                    </a> -->

                    <button type='submit' class="btn complete-reg-btn">
                        Login
                    </button>

                    <p><a href="{% url 'app:create_account' %}">I don't have an account yet </a></p>
                </div>
            </form>
        </div>
    </div>
    <!-- * App Capsule -->

    <!-- ///////////// Js Files ////////////////////  -->
    <!-- Jquery -->
    <script src="{% static "assets/js/lib/jquery-3.4.1.min.js" %}"></script>
    <!-- Bootstrap-->
    <script src="{% static "assets/js/lib/popper.min.js" %}"></script>
    <script src="{% static "assets/js/lib/bootstrap.min.js" %}"></script>
    <!-- Ionicons -->
    <script type="module" src="https://unpkg.com/ionicons@5.0.0/dist/ionicons/ionicons.js"></script>
    <!-- Owl Carousel -->
    <script src="{% static "assets/js/plugins/owl-carousel/owl.carousel.min.js" %}"></script>
    <!-- jQuery Circle Progress -->
    <script src="{% static "assets/js/plugins/jquery-circle-progress/circle-progress.min.js" %}"></script>
    <!-- Base Js File -->
    <script src="{% static "assets/js/base.js" %}"></script>


    <script>
        setTimeout(() => {
            notification('notification-welcome', 5000);
        }, 2000);
    </script>

</body>

</html>