app/urls.py
from django.urls import path, include
from app.views import (
    IndexView,
    CreateAccountView,
    LoginView,
    GenerateOTPView,
    OTPVerificationView,
    RegisterView,
    RecordPlayView,
    SetupVoiceView,
    TapListenView,
    VerifyProceedView,
    ProvidersView,
    MobileRechargeView,
    BillFoundView,
    DTHRechargeView,
    MobilePostpaidView,
    LandlineView,
    ElectricityView,
    WaterView,
    PipedgasView,
    FASTagView,
    LoanRepaymentView,
    BroadbandView,
    LpgGasView,
    InsurancePaymentView,
    SubscriptionView,
    SendMoneyView,
    SendVoiceMoneyView,
    RequestMoneyView, 
    RequestVoiceMoneyView,
    VoiceAuthenticationView,
    ScanPayView,
    DashboardView,
    SettingView,
    PersonalInformationView,
    NotificationEmailsView,
    PrivacySecurityView,
    AboutView,
    HelpFeedbackView,
    EditMobileNumberView,
    EditLanguageView,
    DataPersonalizationView,
    BlockedPeopleView,
    HowPeopleView,
    TermsServicesView,
    PrivacyPolicyView,
    SoftwareLicenseView,
    UserProfileView,
    DrawNumberGameView,
    GetOTPFromVoiceView,
    LogoutView,
    GetNumberFromVoiceView,
    GetGameResultSuccessView,
    GetGameResultFailureView,
    AskToPlayGameView,
    PaymentSuccessfulView,
    InvoiceGeneratorView,
    DisplayInvoiceView,
    RequestSearchUserView,
    RequestSuccessView,
    RedirectView,
    RazorpayPaymentSuccessfulView,
    RazorpayPaymentUnsuccessfulView,
    RazorpayPaymentHandlerView,
    PayWithCCAvenueView,
    CCAvenueResponseView,
    CreateMerchantAccountView,
    MerchantRegistrationView,
    MerchantLoginView,
    MerchantDashboardView,
    ListProductsView,
    AddProductView,
    UpdateProductView,
    DeleteProductView,
    load_states,
    load_cities,
    ListProductVariationView,
    AddProductVariationView,
    DeleteProductVariationView,
    UpdateProductVariationsView,
    ListPurchaseView,
    AddPurchaseView,
    AddSaleView,
    AddSellReturnView,
    AddStockTransferView,
    AddStockAdjustmentsView,
    DeletePurchaseView,
    DeleteSellReturnView,
    DeleteSaleView,
    DeleteStockTransferView,
    DeleteStockAdjustmentView,
    AddExpenseView,
    DeleteExpenseView,
    AddExpenseCategoryView,
    DeleteExpenseCategoryView,
    AddTaxRatesView,
    UpdateTaxRatesView,
    DeleteTaxRatesView,
    AddBrandsView,
    UpdateBrandsView,
    DeleteBrandsView,
    AddUnitsView,
    UpdateUnitsView,
    DeleteUnitsView,
    AddTaxGroupView,
    DeleteTaxGroupView,
    OrderSummaryView,




    AboutUsView,
    ShopView,
    retrieveData,
    retrieveOneData,
    CheckoutView,
    AddCouponView,
    PaymentView,
    search,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    bycategoryelectronics,
    bycategorybooks,

)
from app import views


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create_account/', CreateAccountView.as_view(), name='create_account'),
    path('login/', LoginView.as_view(), name='paybill_login'),   
    path('otp/', GenerateOTPView.as_view(), name='otp'),
    path('otp/payment/', GenerateOTPView.as_view(), name='otp_payment'),
    path('otp_verification/', OTPVerificationView.as_view(), name='otp_verification'),   
    path('otp_payment_verification/', OTPVerificationView.as_view(), name='otp_payment_verification'),   
    path('otp_voice_verification/', GetOTPFromVoiceView.as_view(), name='otp_voice_verification'),    
    path('register/', RegisterView.as_view(), name='register'),
    path('record_play/', RecordPlayView.as_view(), name='record_play'),
    path('setup_voice/', SetupVoiceView.as_view(), name='setup_voice'),
    path('tap_listen/', TapListenView.as_view(), name='tap_listen'),
    path('verify_proceed/', VerifyProceedView.as_view(), name='verify_proceed'),
    path('aboutus/', AboutUsView.as_view(), name='aboutus'),
    path('providers/', ProvidersView.as_view(), name='providers'),
    path('providers/mobile_recharge/', MobileRechargeView.as_view(), name='mobile_recharge'),
    path('providers/bill_found/', BillFoundView.as_view(), name='bill_found'),
    path('providers/dth_recharge/', DTHRechargeView.as_view(), name='dth_recharge'),
    path('providers/mobile_postpaid/', MobilePostpaidView.as_view(), name='mobile_postpaid'),  
    path('providers/landline/', LandlineView.as_view(), name='landline'),  
    path('providers/electricity/', ElectricityView.as_view(), name='electricity'),  
    path('providers/water/', WaterView.as_view(), name='water'),  
    path('providers/piped_gas/', PipedgasView.as_view(), name='piped_gas'),  
    path('providers/FASTag/', FASTagView.as_view(), name='fastag'),  
    path('providers/loan_repayment/', LoanRepaymentView.as_view(), name='loan_repayment'),  
    path('providers/broadband/', BroadbandView.as_view(), name='broadband'),  
    path('providers/lpg_gas/', LpgGasView.as_view(), name='lpg_gas'),
    path('providers/insurance_payment/', InsurancePaymentView.as_view(), name='insurance_payment'),
    path('providers/subscription/', SubscriptionView.as_view(), name='subscription'),





    path('shop/', ShopView.as_view(), name='shop'),
    path('shopdetail/', retrieveData.as_view(), name='shop'), 
    path('shopdetail/<slug>/', retrieveOneData.as_view(), name='shopdetail'),
    path('search/', views.search, name='search'),
    path('category/books/', views.bycategorybooks, name='bycategorybooks'),
    path('category/electronics/', views.bycategoryelectronics, name='bycategoryelectronics'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),











    path('send_money/', SendMoneyView.as_view(), name='paybills_send_money'),
    path('send_voice_money/', SendVoiceMoneyView.as_view(), name='send_voice_money'),
    path('request_money/<int:user_id>', RequestMoneyView.as_view(), name='request_money'),
    path('request_voice_money/', RequestVoiceMoneyView.as_view(), name='request_voice_money'),
    path('voice_authentication/', VoiceAuthenticationView.as_view(), name='voice_authentication'),
    path('scan_pay/', ScanPayView.as_view(), name='scan_pay'), 
    path('dashboard/', DashboardView.as_view(), name='dashboard'), 
    path('setting/', SettingView.as_view(), name='setting'), 
    path('personal_info/', PersonalInformationView.as_view(), name='personal_info'), 
    path('notification_email/', NotificationEmailsView.as_view(), name='notification_email'), 
    path('privacy_security/', PrivacySecurityView.as_view(), name='privacy_security'), 
    path('about/', AboutView.as_view(), name='about'), 
    path('help_feedback/', HelpFeedbackView.as_view(), name='help_feedback'), 
    path('personal_info/edit_mobile_number/', EditMobileNumberView.as_view(), name='edit_mobile_number'), 
    path('personal_info/edit_language/', EditLanguageView.as_view(), name='edit_language'),      
    path('privacy_security/data_personalization/', DataPersonalizationView.as_view(), name='data_personalization'),      
    path('privacy_security/blocked_people/', BlockedPeopleView.as_view(), name='blocked_people'),      
    path('privacy_security/how_people_find_you/', HowPeopleView.as_view(), name='how_people_find_you'),      
    path('about/terms_services/', TermsServicesView.as_view(), name='terms_services'),      
    path('about/privacy_policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),      
    path('about/software_license/', SoftwareLicenseView.as_view(), name='software_license'), 
    path('dashboard/user_profile/', UserProfileView.as_view(), name='user_profile'),      
    path('draw_number_game/', DrawNumberGameView.as_view(), name='draw_number_game'),      
    path('get_number_game/', GetNumberFromVoiceView.as_view(), name='get_number_game'),      
    path('logout/', LogoutView.as_view(), name='logout'),
    path('get_game_result_success/', GetGameResultSuccessView.as_view(), name='get_game_result_success'),
    path('get_game_result_failure/', GetGameResultFailureView.as_view(), name='get_game_result_failure'),
    path('ask_to_play_game/', AskToPlayGameView.as_view(), name='ask_to_play_game'),
    path('payment_successful/', PaymentSuccessfulView.as_view(), name='payment_successful'),    
    path('get_invoice/', InvoiceGeneratorView.as_view(), name='get_invoice'),
    path('display_invoice/<int:bill_id>/', DisplayInvoiceView.as_view(), name='display_invoice'),
    path('search_user/', RequestSearchUserView.as_view(), name='search_user'),
    path('request_successful/', RequestSuccessView.as_view(), name='request_successful'),    
    path('send_money/', SendMoneyView.as_view(), name='paybills_send_money'), 
    path('send_money/razorpay_payment_handler/', RazorpayPaymentHandlerView.as_view(), name='razorpay_payment_handler'), 
    path('razorpay_payment_successful/', RazorpayPaymentSuccessfulView.as_view(), name='razorpay_payment_successful'),
    path('razorpay_payment_unsuccessful/', RazorpayPaymentUnsuccessfulView.as_view(), name='razorpay_payment_unsuccessful'),
    #path('razorpay_payment/',PayWithRazorpayView.as_view(), name='razorpay_payment'),
    path('ccavenue_payment/',PayWithCCAvenueView.as_view(), name='ccavenue_payment'),
    path('ccavenue_response/', CCAvenueResponseView.as_view(), name='ccavenue_response'),
    #path('create_merchant_account/', CreateMerchantAccountView.as_view(), name='create_merchant_account'),
    path('create_merchant_account/', MerchantRegistrationView.as_view(), name='create_merchant_account'),

paybills/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
"""
from app.views import (
    UserLogin,
    UserLogout,
    UserRegistration,
    UserResetPwd,
)
"""

urlpatterns = [
    #path('', RedirectView.as_view(pattern_name='index')),

    #path('admin/', admin.site.urls),
    path('paybills_admin/', admin.site.urls),
    #path('login/', UserLogin.as_view(template_name='app/login.html'), name='user_login'),
    #path('logout/', UserLogout.as_view(), name='user_logout'),
    #path('registration/', UserRegistration.as_view(), name='registration'),
    #path('reset-password/', UserResetPwd.as_view(), name='reset_password'),
    #path('paypal/', include('paypal.standard.ipn.urls')),    
    # path('', include('app.urls')),
    path('', include(('app.urls', 'app'), namespace='app')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/templates/app/bank_list.html
{% extends 'app/wallet_page.html' %}
{% load static %}

{% block bank %}
    <article class="blog_item" >
        <div class="blog_item_img">
            <img class="card-img rounded-0" src="../../static/img/banner/profile_banner.png" alt="">
            <a href="#" class="blog_item_date">
                <h3><div class="icon"><i class="fa fa-bank" aria-hidden="true"></i></div></h3>

            </a>
        </div>
        <div class="blog_details">
            <h2>Bank Information</h2><hr>
            <div class="input-group-icon mt-10">
                {% for bank in bank_list %}
                    <ul class="list cat-list">
                        <li><a href="{{ bank.get_absolute_url }}">
                            <b style="color: black">Bank Account:</b>&emsp;{{ bank }}</a></li><hr>
                    </ul>
                    {% empty %}
                    <li><em>There are currently no bank accounts available.</em></li>
                {% endfor %}
            </div>
            <br>
            <div class="input-group-icon mt-10">
                 <a href="{% url 'app:bank_create' %}"
                    class="btn rounded-0 btn-outline-primary">Add Bank</a>
            </div>
        </div>
    </article>

{% endblock %}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Easy Pay</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <!--<link rel="shortcut icon" type="image/x-icon" href="../static/img/favicon.png"> -->
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'app:index' %}">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="{% url 'app:index' %}">Home</a></li>
                                        {% if perms.app.add_transaction%}
                                            <li><a href="#">Activity</a></li>
                                        {% endif %}
                                        {% if perms.app.add_transaction %}
                                            <li><a href="#">Send & Request</a>
                                        {% endif %}
                                        {% if perms.app.add_account%}
                                            <li><a href="#">Wallet</a></li>
                                        {% endif %}
                                        {% if perms.app.change_profile %}
                                            <li><a href="#">User Profile</a></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                                <div>
                                    {% if user.is_authenticated %}
                                        <div class="book_btn d-none d-lg-block"><a href="#">Log Out</a></div>
                                    {% else %}
                                        <div class="book_btn d-none d-lg-block"><a href="#">Login</a></div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block content %}
        This is default content!
    {% endblock %}

    <!-- footer start -->
    <footer class="footer">
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                    <div class="row">
                        <div class="col-xl-12">
                            <p class="copy_right text-center">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer end  -->

    <!-- link that opens popup -->

    <!-- JS here -->
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/gijgo.min.js' %}"></script>
    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>

    <script src="{% static 'js/main.js' %}"></script>
    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }
        });
        $('#datepicker2').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
                rightIcon: '<span class="fa fa-caret-down"></span>'
            }

        });
    $(document).ready(function() {
    $('.js-example-basic-multiple').select2();
});
    </script>
</body>

</html>

app/templates/app/card_create.html
{% extends 'app/wallet_page.html' %}
{% load static %}

{% block card %}

<!--================Blog Area =================-->
<article class="blog_item" >
    <div class="blog_item_img">
        <img class="card-img rounded-0" src="{% static 'img/banner/profile_banner.png' %}" alt="">
        <a href="#" class="blog_item_date">
            <h3><div class="icon"><i class="fa fa-credit-card" aria-hidden="true"></i></div></h3>

        </a>
    </div>
    <div class="blog_details">
        <h2>Add Card</h2><hr>
        <form action="{% url 'app:card_create' %}" method="post">
            {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    <ul>
                        {% for field in form %}
                            {% for error_msg in field.errors %}
                                <li>{{ error_msg|escape }}</li>
                            {% endfor %}
                        {% endfor %}
                        {% for error_msg in form.non_field_errors %}
                            <li>{{ error_msg|escape }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="input-group-icon mt-10">
                <div class="icon"><i class="fa fa-credit-card" aria-hidden="true"></i></div>
                <div class="form-select" id="default-select">
                    {{ form.card_type }}
                </div>
            </div>
            <div class="input-group-icon mt-10">
                <div class="icon"><i class="fa fa-credit-card" aria-hidden="true"></i></div>
                <input type="text" class="single-input" name="{{ form.card_number.html_name }}"
                       id="{{ form.card_number.id_for_label }}" placeholder="Card Number (16 digits)" required>
            </div>
            <div class="input-group-icon mt-10">
                <div class="icon"><i class="fa fa-user" aria-hidden="true"></i></div>
                <input type="text" class="single-input" name="{{ form.owner_first_name.html_name }}"
                       id="{{ form.owner_first_name.id_for_label }}" placeholder="Card Holder First Name" required>
            </div>
            <div class="input-group-icon mt-10">
                <div class="icon"><i class="fa fa-user" aria-hidden="true"></i></div>
                <input type="text" class="single-input" name="{{ form.owner_last_name.html_name }}"
                       id="{{ form.owner_last_name.id_for_label }}" placeholder="Card Holder Last Name" required>
            </div>
            <div class="input-group-icon mt-10">
                <div class="icon"><i class="fa fa-lock" aria-hidden="true"></i></div>
                <input type="text" class="single-input" name="{{ form.security_code.html_name }}"
                       id="{{ form.security_code.id_for_label }}" placeholder="Security Code (3 digits)" required>
            </div>
            <div class="input-group-icon mt-10">
                <div class="icon"><i class="fa fa-calendar" aria-hidden="true"></i></div>
                <input class="single-input" name="{{ form.expiration_date.html_name }}"
                       id="{{ form.expiration_date.id_for_label }}" type="text"
                       onfocus="(this.type='date')" placeholder="Expiration Date" required>
            </div>

            <br>
            <div class="input-group-icon mt-10">
                <button class="button rounded-0 btn btn-outline-primary" type="submit">Add</button> &nbsp;&nbsp;
            </div>
        </form>
    </div>
</article>
    <!--================Blog Area =================-->
{% endblock %}

app/templates/app/incomplete_list.html
{% extends 'app/transaction_page.html' %}
{% load static %}

{% block incomplete %}
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row" >
                <div class="col-lg-8 mb-5 mb-lg-0" >
                    <article class="blog_item" >
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="../../static/img/banner/profile_banner.png" alt="">
                            <a href="#" class="blog_item_date">
                                <h3><div class="icon"><i class="flaticon-money" aria-hidden="true"></i></div></h3>
                            </a>
                        </div>
                        <div class="blog_details">
                            <h2>Incomplete Payment</h2><hr>
                            <div class="input-group-icon mt-10">
                                {% for tran in tran_receiver_list %}
                                    <ul class="list cat-list">
                                        <li><b style="color: black"><font size="4">Send To: {{ tran.creator }}</font></b>&emsp;
                                            <a href="{% url 'app:incomplete_payment' tran.pk %}">${{ tran.amount }} USD ({{ tran.description }})</a>
                                        </li><hr>
                                    </ul>
                                    {% empty %}
                                    <li><em>There are currently no incomplete payments.</em></li>
                                {% endfor %}
                            </div>
                            <br>
                        </div>
                    </article>

                    <article class="blog_item" >
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="../../static/img/banner/profile_banner.png" alt="">
                            <a href="#" class="blog_item_date">
                                <h3><div class="icon"><i class="flaticon-money-2" aria-hidden="true"></i></div></h3>
                            </a>
                        </div>
                        <div class="blog_details">
                            <h2>Requests From You</h2><hr>
                            <div class="input-group-icon mt-10">
                                {% for tran in tran_creator_list %}
                                    <ul class="list cat-list">
                                        <li><b style="color: black"><font size="4">Request To: {{ tran.receiver }}</font></b>&emsp;
                                            <a href="{% url 'app:incomplete_request' tran.pk %}">${{ tran.amount }} USD ({{ tran.description }})</a>

                                        </li><hr>
                                    </ul>
                                    {% empty %}
                                    <li><em>There are currently no requests incompleted.</em></li>
                                {% endfor %}
                            </div>
                            <br>
                        </div>
                    </article>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Links</h4>
                            <ul class="list cat-list">
                                <li>
                                    <a href="{% url 'app:activity' %}">
                                        <p>View Activity</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'app:account' %}" >
                                        <p>Payment Method</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'app:profile' %}" >
                                        <p>User Profile</p>
                                    </a>
                                </li>
                            </ul>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

app/templates/app/payment_success.html
{% extends 'app/transaction_page.html' %}
{% load static %}

{% block incomplete %}
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row justify-content-md-center" >
                <div class="col-lg-8 mb-5 mb-lg-0" >
                    <article class="blog_item" >
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="{% static 'img/banner/profile_banner.png' %}" alt="">
                            <a href="#" class="blog_item_date">
                                <h3><div class="icon"><i class="flaticon-money-2"></i></div></h3>

                            </a>
                        </div>
                        <div class="blog_details">
                            <h1>Payment Completed!</h1>

                            <h4><br>Check <a href="{% url 'incomplete' %}"><b>Incomplete Transactions >>></b></a></h4>
                        </div>
                    </article>
                </div>

            </div>
        </div>
    </section>

{% endblock %}

app/templates/app/paypal_canceled.html
{% extends 'app/transaction_page.html' %}

{% block content %}
    <h1>
        Your payment was canceled
    </h1>
    <p>
        Your payment has been canceled
    </p>
{% endblock %}

app/templates/app/user_profile.html
{% extends 'app/base.html' %}

{% block content %}
    <!-- bradcam_area_start  -->
    <div class="bradcam_area breadcam_bg bradcam_overlay">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>User Profile</h3>
                        <p><a href="{% url 'app:index' %}">Home /</a> User Profile</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- bradcam_area_end  -->

    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row" >
                <div class="col-lg-8 mb-5 mb-lg-0" >
                    <div class="blog_left_sidebar" >
                        <article class="blog_item" >
                            {% block profile_form %}
                                default content
                            {% endblock %}
                        </article>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">User Account</h4>
                            <ul class="list cat-list">
                                <li>
                                    <a href="{% url 'app:account' %}">
                                        <p>View Balance</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'app:activity' %}">
                                        <p>View Activity</p>
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'app:reset_password' %}" >
                                        <p>Change Password</p>
                                    </a>
                                </li>
                            </ul>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}